### PR TITLE
Allow for larger input from KCL

### PR DESCRIPTION
**Pull request by ajmath**
I was getting exceptions from the scanner.  Scan method for the events in my kinesis stream about the line being too larger.  A suggestion on stackoverflow was to use a reader.ReadBytes instead of scanner.Scan.  My stream now works but I have not done extensive testing.

### CODE REVIEW

**Comment by nrocine** [comment]
I also ran into this issue. I tried ajmath's fork and it solved the issue. We are now pulling the default 10,000 records per get for the MultiLangDaemon with no issues.

Thanks ajmath.

**Comment by nieksand** [comment]
can you link to the stackoverflow post in question?

**Comment by ajmath** [comment]
I think it was this one: http://stackoverflow.com/questions/21124327/how-to-read-a-text-file-line-by-line-in-go-when-some-lines-are-long-enough-to-ca

**Comment by nieksand** [comment]
Merged.  Sorry for the delayed turn around

**Pull request merged**
